import type { Metadata } from "next";
import "./globals.css";
import Footer from "../components/Footer/Footer"; 
import { WeatherProvider } from "@/context/WeatherContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
    shortcut: "/favicon.svg",
    apple: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <WeatherProvider>
          {children}
          <Footer />
        </WeatherProvider>
      </body>
    </html>
  );
}
